### ISSUE TITLE
[BUG] Tool always starts between 2 screens with a dual-screen-setup

### ISSUE THREAD

**Issue by wookiefriseur** [darkdks/KF2ServerTool#13]
**Describe the bug**
When using 2 Screens the Tool starts inbetween both screens for me.

**To Reproduce**
1. Have 2 screens
2. Run the tool
3. ????
4. Profit

**Expected behavior**
Should show up on only one of the screens.

**Screenshots**
...

**Desktop (please complete the following information):**
 - OS: Windows 10 64bits
 - Version of the tool 1.3.4 and latest compiled code

**Additional context**
Use `poScreenCenter` instead of `poDesktopCenter` or save the last position in the INI file then it happens only on the first run (I think it currently saves the window size, could add position).

**Comment by darkdks** [comment]
possibly fixed in version 1.3.5, reopen if not.
Thank you for your help! ;)
