### ISSUE TITLE
Invalid arguments with -config

### ISSUE THREAD

**Issue by Lartza** [darkdks/KF2ServerTool#15]
**Describe the bug**
Running the tool using -config with a confirmed working ini causes the tool to not work. Both -info and -addmap have the same behaviour while both without -config work.

**To Reproduce**
1. Run the tool with `-config KFServerToolCMD.ini -info`
2. Tool prints `Option: Custom ini is set to KFServerToolCMD2.ini` and `Press ENTER`
3. Press enter
4. See error `Error: status: Invalid arguments and no server info`

**Expected behavior**
Tool works with a specified config file

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version of the tool 1.2.5?

**Comment by darkdks** [comment]
Hello Lartza, 
I was successful in reproducing the bug, and I believe I already solved it. But the only thing is that my linux build environment is no longer configured because I haven't worked with it for years.
I believe that soon I will release a updated version and with many problems solved (this version from git to linux was made in 2018).
Also nice to see people from linux using the tool. I hope these problems would be fixed soon.

**Comment by darkdks** [comment]
Can you confirm if the version in Beta branch resolve this issue?
https://github.com/darkdks/KF2ServerTool/blob/beta-debug/code/KF2ServerToolCMD

**Comment by Lartza** [comment]
It does not. For starters an easy fix. The default config should be Binaries instead of /Binaries like the KFGame lines I think. (Searching for: /home/darkdks/kf2server//Binaries/Win64/KFGameSteamServer.bin.x86_64)

But also, you have a hardcoded path somewhere or the config isn't read correctly.

```
[steam@sauna kf2]$ ./KF2ServerToolCMD -config KFServerToolCMD_Server2.ini -info
./KF2ServerToolCMD
-config
KFServerToolCMD_Server2.ini
-info
Option: Custom ini is set to KFServerToolCMD_Server2.ini
Error: Killing Floor 2 server not found.
Check if the app is in server folder or the KFServerToolCMD_Server2.ini is configured correctly.
Searching for: /home/darkdks/kf2server/Binaries/Win64/KFGameSteamServer.bin.x86_64
Use -help to show help
```
Additional non-important issue I found is that the tool doesn't understand absolute paths.

```
[steam@sauna kf2]$ ./KF2ServerToolCMD -config /home/steam/kf2/KFServerToolCMD_Server2.ini -info
./KF2ServerToolCMD
-config
/home/steam/kf2/KFServerToolCMD_Server2.ini
-info
Option: Custom ini is set to /home/steam/kf2/KFServerToolCMD_Server2.ini
Ini file not found, writing default config file in: /home/steam/kf2//home/steam/kf2/KFServerToolCMD_Server2.ini
Exception EFCreateError in module KF2ServerToolCMD at 000000000050199F.
Cannot create file "/home/steam/kf2/home/steam/kf2/KFServerToolCMD_Server2.ini". System error:    2.
```

Config on previous tests

```
[PATHS]
UseCustomServerPath=1
CustomServerPath=/home/steam/kf2
SteamCmdTool=/home/steam/Steam/steamcmd.sh
ServerEXE=Binaries/Win64/KFGameSteamServer.bin.x86_64
KFGameIni=KFGame/Config/Server2/LinuxServer-KFGame.ini
KFEngineIni=KFGame/Config/Server2/LinuxServer-KFEngine.ini
KFWebIni=KFGame/Config/Server2/KFWeb.ini
```

Deleted config to let the tool create a new one

```
[steam@sauna kf2]$ ./KF2ServerToolCMD -config KFServerToolCMD_Server2.ini
./KF2ServerToolCMD
-config
KFServerToolCMD_Server2.ini
Option: Custom ini is set to KFServerToolCMD_Server2.ini
Ini file not found, writing default config file in: /home/steam/kf2/KFServerToolCMD_Server2.ini
```

But -info still fails after editing the created config to correct folders

```
[steam@sauna kf2]$ ./KF2ServerToolCMD -config KFServerToolCMD_Server2.ini -info
./KF2ServerToolCMD
-config
KFServerToolCMD_Server2.ini
-info
Option: Custom ini is set to KFServerToolCMD_Server2.ini
Error: Killing Floor 2 server not found.
Check if the app is in server folder or the KFServerToolCMD_Server2.ini is configured correctly.
Searching for: /home/darkdks/kf2server/Binaries/Win64/KFGameSteamServer.bin.x86_64
Use -help to show help
```

```
[PATHS]
UseCustomServerPath=1
CustomServerPath=/home/steam/kf2
ServerEXE=Binaries/Win64/KFGameSteamServer.bin.x86_64
KFGameIni=KFGame/Config/Server2/LinuxServer-KFGame.ini
KFEngineIni=KFGame/Config/Server2/LinuxServer-KFEngine.ini
KFWebIni=KFGame/Config/Server2/KFWeb.ini
SteamCmdTool=/home/steam/Steam/steamcmd.sh

[CYCLEOPTIONS]
includeSeparators=0
cycleSortType=keepsame

;--------- CYCLE SORT OPTIONS --------
;  cycleSortType : How the tool will sort game cycle
;         keepsame: will not modify the current order
;         byname: will sort by name
;         bytype: will by type (offical, custom)
;  includeSeparators : include separators when sort byname or bytype is set
```

Without -config is broken too now (It even worked with /Binaries before). Removing the slash of course does not help. This is identical to first config but Server1

```
[steam@sauna kf2]$ ./KF2ServerToolCMD -info
./KF2ServerToolCMD
-info
Error: Killing Floor 2 server not found.
Check if the app is in server folder or the KFServerToolCMD.ini is configured correctly.
Searching for: /home/darkdks/kf2server//Binaries/Win64/KFGameSteamServer.bin.x86_64
Use -help to show help
```

**Comment by darkdks** [comment]
Ups. The compiled file is using my debug environment lol. Sorry about that, my bad. 
I updated the bin right now, after generating a new config file just change:
UseCustomServerPath=1
CustomServerPath=/home/steam/kf2

**Comment by Lartza** [comment]
Everything seems to work!
