### ISSUE TITLE
Start server botton disappear

### ISSUE THREAD

**Issue by mgick** [darkdks/KF2ServerTool#18]
botton disappear in main window

1. I have archive with previous version and outdated server. After unpacking program give me option for update, I updated and bam boton disappear.

Windows 10 64bit
https://i.imgur.com/w3Z7Xp5.png

**Comment by mgick** [comment]
Can confirm. Old version from archive: https://i.imgur.com/aEVZiOH.png

**Comment by kaleb112494** [comment]
Can also confirm. 1.3.5 has missing "start server" button.

**Comment by darkdks** [comment]
Sorry for the delay.
Fixed in the release 1.3.6. Thanks for the report =)
