### ISSUE TITLE
restart if crashed

### ISSUE THREAD

**Issue by mgick** [darkdks/KF2ServerTool#19]
Hi, please add feature restart server, if crashed. today I have several crashs on my servers.

**Comment by darkdks** [comment]
Hey, it's pretend to be a nice feature.
Check [this ](https://github.com/darkdks/KF2ServerTool/blob/master/code/KF2ServerTool.exe).
Please test as much as you can the feature and give me a feedback of the tests to validate for a new update.

**Comment by mgick** [comment]
it works, tested on 2 servers!
