### ISSUE TITLE
why you close autoupdate request?

### ISSUE THREAD

**Issue by mgick** [darkdks/KF2ServerTool#22]
^

**Comment by darkdks** [comment]
You did not specify details about what and also did not followed github good practices to make the request.
However, currently the tool covers both updating the tool itself and updating the server. I have no plans to do the automatic update as it is a user option and he needs to make sure an update it.

**Comment by mgick** [comment]
I mean update the server not a tool

**Comment by darkdks** [comment]
believe updates should be ,scheduled. Auto updating the server involves many processes that can corrupt if it's unexpectedly canceled(like close process and shutdown), in addition this checking consumes a lot of the server.
If you still insist, you can just do a .bat with steamcmd.exe arguments and schedule it in the windows task scheduler. But seriously, I don't think it's a good practice. Servers updates need to be planed and scheduled, without servers running.
About the issues being closed, I believe you are a new user, so you should be unaware of how github works, but if you are asking for new things, try to be the most cordial, specific, detailed in your idea, so as not to sound rude and generate lack of understanding.
For bug report we have also a template that you should follow.
I hope you understand.
