### ISSUE TITLE
I don't see my server in LAN or Internet 

### ISSUE THREAD

**Issue by humam2104** [darkdks/KF2ServerTool#23]
My friend can find my server though which is weird! I would appreciate it if you fix this. thx
Note: I'm still able to join through open 127.0.0.1

**Comment by darkdks** [comment]
592/5000
Hello, Humam2104.
If your friend can see and join in your server and you cannot see your own server, this is not a problem with the tool itself or with the server. It is more of a modem/NAT/firewall problem, some games need a technology in the modem called "Nat loopback" to be able to see itself as a host, kf2 server needs this, it may be your case (your modem or router does not have this feature).
For this case, you must enter the loopback address (127.0.0.1) when you want to enter the host itself (like u said).
Anyway this is not a problem with the tool or with the server installation.
I hope you understand.

**Comment by darkdks** [comment]
Hello, Humam2104.
If your friend can see and join in your server and you cannot see your own server, this is not a problem with the tool itself or with the server. It is more of a modem/NAT/firewall problem, some games need a technology in the modem called "Nat loopback" to be able to see itself as a host, kf2 server needs this, it may be your case (your modem or router does not have this feature).
For this case, you must enter the loopback address (127.0.0.1) when you want to enter the host itself (like u said).
Anyway this is not a problem with the tool or with the server installation.
I hope you understand.

**Comment by humam2104** [comment]
Greetings Samuel,

The thing is that I can see my server while opening it regularly from the KF2server.bat, and I’ve tried another tool called simple kf2 server and it works fine but your tools is better and more advanced.. sorry for not mentioning this earlier.

Regards,

Eng. Humam Ghazal

[BS] Bachelor’s of Science in Civil Engineering

LinkedIn<https://www.linkedin.com/in/humam-ghazal-875739136/edit/topcard/>

**Comment by darkdks** [comment]
Oh, it changes things.
Does this happen in the same installation (you see the server by .bat but you don't see it when executed by the tool)?
If so, I have no idea why you don't see it, since basically KF2ServerTool calls the host's executable just like .bat does. Many people use this tool and I have never been reported something like that. But I will keep following this to a possible variable in your situation. 
If you managed to get around this in any way please report.
