### ISSUE TITLE
Initial server setup

### ISSUE THREAD

**Issue by Raieverr** [darkdks/KF2ServerTool#24]
**Describe the bug**
1. On initial server set (Selecting "Install a new server"), it does not matter what folder is selected it will default download the "game" folder to your desktop (at least my desktop, as I have the files extracted into a "Servers" folder on my desktop)

2. After files are downloaded, the program asks for the directory where server is installed (Existing server files), and then fails when selecting due to not having the folder "STEAMCMD" and steamcmd.exe in that folder.

**To Reproduce**
1. Open KF2ServerTool and Select "Install on new server"
2. Select the designated folder for install (For me, Desktop -> Servers -> KFServers)
3. Download will start after anonymous login, and game folder will be placed on desktop, with no install happening inside designated folder. (SteamCMD will download all its files, and create a steamapps folder with just "libraryfolders.vdf" in it)
4. Have to manually run steamcmd, and do "app_update 232130" for files to properly be installed. (For me Servers -> KFServers -> SteamCMD -> Steamapps -> Common -> kf2server)

Steps for problem two:
1. After server files are downloaded, re-open KFServerTool and select existing installation
2. The folder in question needs to have a folder called STEAMCMD and steamcmd.exe placed inside of it (Why?)
3. Create folder SteamCMD, and copy steamCMD.exe into this folder
4. Run KFServerTool again, and bam. Config opens.

**Expected behavior**
1. Start program and select "Install on new server"
2. Select designated folder for server files
3. Files download to designated folder not desktop
4. Re-run KFServerTool, select existing install, choose your server folder, server starts

**Screenshots**
![KF2Server](https://user-images.githubusercontent.com/48493132/97838828-42705280-1c9e-11eb-8a71-98db2071304b.PNG)
![problem2](https://user-images.githubusercontent.com/48493132/97840276-f7a40a00-1ca0-11eb-9a5f-9df54c7f4a1f.PNG)

**Desktop (please complete the following information):**
 - OS: Win 10 64bit
 - Version of the tool: 1.3.7

**Additional context**
A basic guide written on the github on downloading + installing would be fantastic. I noticed that when run, you need to have a copy of steamCMD in the server files folder or else it will fail to update/download and this messed with me for a while. A simple guide such as:

1. Download KFServerTool, extract to your folder of choice.
2. Run KFServerTool and select existing server, or install on new server.
3. Choose location of existing server, or new server download location.
4. Allow KFServerTool to download game files, and close.
5. Navigate to your server folder ->SteamCMD, copy the SteamCMD.exe file, then navigate to Steamapps -> Common -> KF2Server, create a folder called "STEAMCMD", and then paste the SteamCMD.exe inside of it.
6. Navigate to your server folder ->SteamCMD -> Steamapps -> Common -> KF2Server, Run the KF2Server.bat file. Allow permissions to your firewall if prompted, and once you see "DevOnline: Sending out playfab", close the window.
7. Run the KFServerTool again, this time selecting "Existing server" and choose your server folder ->SteamCMD -> Steamapps -> Common -> KF2Server.
8. Enjoy!

**Comment by Raieverr** [comment]
Note/Edit:
I just noticed the wiki is available to edit, I would like to confirm the bugs/issues above prior to changing anything but would be more than happy to type up a quick guide on setup after.

**Comment by darkdks** [comment]
I'll try to reproduce this and work for a fix as soon as possible. Thank your for the report. I bring news soon

**Comment by Raieverr** [comment]
If you need more details / video proof you can add me on discord Raiever#6071, and I can screenshare with you to show you what I am talking about. Thank you for the hard work so far!

**Comment by darkdks** [comment]
I think i get it.
Can you test this https://github.com/darkdks/KF2ServerTool/blob/master/code/KF2ServerTool.exe and give me a feedback if it is fixed? (you still need steamcmd/steamcmd from release) Thank you

**Comment by Raieverr** [comment]
That fixed the issue of the new server portion! Made a new folder, put new servertool and SteamCMD folder in there.. ran it, selected new install, chose the folder, it downloaded directly there. 

However as you stated, it is still having the issue of trying to detect STEAMCMD in the server install folder. I think this is happening due to this line "SteamCmdTool=STEAMCMD\SteamCmd.exe" inside of the Servertool.ini, and when you install the server in a nested area.

You can test this:
1. Create a folder called whatever (example "KF"), Put the KFServerTool and SteamCMD folder in there.
2. Create a folder INSIDE of that called "server files".
3. Open KFServerTool, and choose the new install, choose the "server files" folder. It will install properly, but DOES not have the SteamCMD inside of it.
4. If you copy steamcmd from KF folder, to the server files folder, it opens as needed.
![Issue2](https://user-images.githubusercontent.com/48493132/98311436-a344a700-1f8c-11eb-8ef7-c1136a616ca0.PNG)

If you choose new install, and use the SAME folder ("KF" in example) that KFServerTool and SteamCMD folder are in, this issue is not present, and you have no issues. So making the program look for SteamCMD folder in the working directory of KFServerTool would fix this.

As well, as a suggestion. After the server downloads and everything is done and closed, you should have KFServerTool run the "KF2Server.bat" file located where ever the files where downloaded.. Would be as easy as waiting say... 30 seconds, then close the .bat file process or something and then restart itself to open up all good to go!

**Comment by darkdks** [comment]
You are right 🥇 , i checked it and just fixed now! Also i accepted your tip about start the server for first tim and added the language dialog for first run. Can you test it again?
If it's ok i'm ready to release as update in tool itself.

**Comment by Raieverr** [comment]
Certainly can, is it via the same download link as before?!

**Comment by darkdks** [comment]
Yes, it's the same, i just updated

**Comment by Raieverr** [comment]
Sure thing, give me 10-15 minutes or so to play with it and I will report back!

**Comment by Raieverr** [comment]
1. Issue with the SteamCMD is resolved!
2. The auto-run portion worked flawless, took a little longer than needed for my pc but probably worth the 2 minutes for folks with slower PC's.
3.  The new language pop-up is clean, worked well.

The only other question I have is, when downloading many maps from a redirect, I run into an issue with the program crashing stating "Out of memory", then no maps show up at all unless I full re-install the server. Have you ever experienced that? (I was downloading something like.. 300+ maps overnight, from this redirect: http://www.goodmods.com/killingfloor2/)

**Comment by darkdks** [comment]
Happy to know that the fix solved the problem, I probably broke this in a past update and didn't even notice.
Thank you very much for the report and help testend it. I have already published the update and new users should download it.   
You commented about the wiki, it is open, feel free to contribute, all help will be welcome.
About your last question I need to analyze the code, probably some memory leak bug, but unfortunately I can't work on it right now, but I put it on a to do list, a future update i will look at it for sure.
Again, thank you very much for your collaboration.

**Comment by Raieverr** [comment]
Thank you for still being active and working on this! It's a life saver and works great. If you need any more testing, or if I find any more issues I will be sure to report it. Keep up the great work!
