### ISSUE TITLE
Error adding item (Map)

### ISSUE THREAD

**Issue by humam2104** [darkdks/KF2ServerTool#25]
![image](https://user-images.githubusercontent.com/41898465/101691556-46a34300-3a88-11eb-9eb2-d9464c55c806.png)
I've added some items to my kf2 server, but adding any more than that creates this error no matter what the map is. Any help?
These are all the maps with errors.
![image](https://user-images.githubusercontent.com/41898465/101691775-a4378f80-3a88-11eb-8767-cf577c4259f4.png)

**Comment by darkdks** [comment]
Can you provide full steps to reproduce the bug?

**Comment by darkdks** [comment]
> same here and it just happened after running the tool and downloading maps

One thing that comes to mind is the path of both the application and the server. Make sure the path does not contain spaces (steam cmd doesn't like that much) and also that the path is not too long. Keep me updated if something changes or if you have more details about. =)

**Comment by humam2104** [comment]
Well, if seemed to be happening only after I add some mods, they appeared in the unknown tab. I uninstalled them and reinstalled them and everything seems to work fine now.
BTW, there seems to be a line needed for players to download maps from the steam workshop while joining the server.
I would recommend an option to add that line

**Comment by darkdks** [comment]
> > same here and it just happened after running the tool and downloading maps
> 
> One thing that comes to mind is the path of both the application and the server. Make sure the path does not contain spaces (steam cmd doesn't like that much) and also that the path is not too long. Also verify the space in the destination disk. Keep me updated if something changes or if you have more details about. =)

About my previous message, someone has commented and removed after my reply lol 
Anyway, happy to know it worked for you (reinstaling the maps). 
Talking about downloading maps from steam workshop for clients, it's "workshop download manager", right? There is already an option to turn this on in the options tab.
