### ISSUE TITLE
Tool switches to objective mode automatically

### ISSUE THREAD

**Issue by humam2104** [darkdks/KF2ServerTool#26]
1. Select Custom game mode
2. Use mods
3. You will see that the tool switches to Objective mode instead of Custom sometimes. Play a game, restart the server and check it

**Comment by humam2104** [comment]
The issue happens when you type something in the "Additional Parameters" Section

**Comment by darkdks** [comment]
Sorry for the delay.
About the bug, are you using english or another language in the tool?

**Comment by humam2104** [comment]
Thanks man.. really appreciate it.. that bug was a nightmare
