### ISSUE TITLE
Workshop Collection URL support?

### ISSUE THREAD

**Issue by ZachFett** [darkdks/KF2ServerTool#28]
I could be missing something here, but is there not a way to use a workshop collection URL for adding custom maps to a server? It'd be very helpful with saving time instead of having to put in the URL for every single map I want to add.

**Comment by humam2104** [comment]
Well, there's a workaround for this:
Go to Settings (assuming you're on windows 10). then search for clipboard and enable clipboard history.
Then copy all the links you want (don't paste them).
Afterwards, open KF2 Server and click Windows+V. It will open everything you've pasted so far, choose the one you want (the order will not be changed if you choose one of the list).

**Comment by darkdks** [comment]
Collections are not supported yet. But there is an easy way to add multiple items. 
Go to the Add > Multiple Workshop Items option;
Click Add in the workshop browser;
Browse your collection and just open the item and click in add(in the top);
Click back(<) and do the process for again another items(you dont need to close de Workshop Browser).
When you finished of adding the maps then you can proced to download and install the items. 
This should save you some time. About the option of collection, it is possible, maybeit will be implemented in the future, but I am very busy with work at the moment =(

**Comment by ZachFett** [comment]
No worries at all, thank you very much for the alternative method there!
