### ISSUE TITLE
"Warning: Warning, Workshop: Unable to download workshop item"

### ISSUE THREAD

**Issue by ThereforeGames** [darkdks/KF2ServerTool#29]
**Describe the bug**
Per the following Steam post, this app is having issues with updating workshop items:

https://steamcommunity.com/app/232090/discussions/1/3409802983885748185/?ctp=2#c3464974615693560835

**To Reproduce**
1. Start a server that has custom maps, watch log

**Expected behavior**
Maps and other workshop items should be able to update on server launch.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version of the tool: 1.4.0

**Additional context**
N/A

**Comment by darkdks** [comment]
Since then, no one has reported anything like it. As it could have been both a user error and a beta error, and there was only this mention, without new incidents, I am closing this issue.
