### ISSUE TITLE
[Req] Add custom gamemodes

### ISSUE THREAD

**Issue by CallyyllaC** [darkdks/KF2ServerTool#3]
It would be awesome if this had the ability to run a server with a custom game mode like controlled difficulty, or any other custom workshop game modes.

**Comment by darkdks** [comment]
It's already possible since of the first versions, you just need to add the param to start the mod in addicional param box. 
Also, If you enter in Addicional Param input box this will show an example. 
Generally the the start mod param is found at item page on workshop.

**Comment by CallyyllaC** [comment]
It works with Mutators, but whenever I add a game mode it doesn't change it plays whatever was in the combo box `?Game=ControlledDifficulty.CD_Survival?DamageDisplay.DmgMut`

**Comment by darkdks** [comment]
Right, its easy to do, i'll add to next update to do list.
