### ISSUE TITLE
New Official Maps not shown

### ISSUE THREAD

**Issue by humam2104** [darkdks/KF2ServerTool#31]
**Describe the bug**
The new update included new maps, but they're not shown in the program.

**To Reproduce**
1. Download the program
2. Download the latest update

**Expected behavior**
The latest maps should be there.

**Screenshots**
![image](https://github.com/darkdks/KF2ServerTool/assets/41898465/95308ba9-1b4b-49c5-8f04-77bd8ac84d6e)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7 32bits, Windows 10 64bits]
 - Version of the tool [e.g. 1.2.2]

**Additional context**

**Comment by darkdks** [comment]
![image](https://github.com/darkdks/KF2ServerTool/assets/34142935/2bddc8ae-c61f-44b9-bec9-2c5ae107a604)
I've checked it in the next release, and a fresh install is showing these maps.
Let me know if still happen. 1.5.0 coming soon!
