### ISSUE TITLE
Self Start up?

### ISSUE THREAD

**Issue by secretwolfie** [darkdks/KF2ServerTool#33]
Hi there, So far this utility does exactly what I need, but I'm looking for means to have the server startup automatically if the server reboots. Is this possible?

**Comment by IvoKintobor** [comment]
if using windows, you could add a shortcut to the kf2server.bat to the startup folder in windows... i think there's startup scripts in linux that would be similar

**Comment by darkdks** [comment]
If you use the server launcher, check out this feature:
![image](https://github.com/darkdks/KF2ServerTool/assets/34142935/eed5e5dc-77f4-4a06-bcf1-9b355b84ba77)
