### ISSUE TITLE
custom order for maps

### ISSUE THREAD

**Issue by IvoKintobor** [darkdks/KF2ServerTool#35]
is there a way to reorder the maps in the server list in game? if done via the webadmin, it'll keep it fine, but then adding a new map reorders everything again to whatever order the server tool wants to, it seems...

also, maybe have a way to add headers between sections of the map list, like a section for mod maps, and a section for official maps (like how it is in the server tool, but have that match the game list)... or if people want to be more picky about their list, they have have it so a particular section is kf1 maps, a section of cod maps, etc

**Comment by pat4005** [comment]
I think that it has nothing to do with the server part, because it's in the server list in a game.

**Comment by darkdks** [comment]
Added a feature to choose how the application will handle map cycle. Check it in version 1.5.0. The option for you is in the Options tab, map sort option, choose the "don't sort". It will keep the map order the same, if you add a new map.
