### ISSUE TITLE
Can't get BETA map into cycle

### ISSUE THREAD

**Issue by billxsand** [darkdks/KF2ServerTool#4]
hey, first off I love this app, it makes the server actually usable!! thank you so much

My issue is that I updated to the beta branch, verified, but the new map from the 2018 christmas beta won't show up in my server maplist

It's supposed to be an official map so it doesn't have a workshop ID. I've also made sure i'm on beta.

**Comment by darkdks** [comment]
Every new official map needs to be updated in the tool to show as official one.
I do it in every important and final update.

But it is just a 'display' thing, how it shows in the app, not the functionality. These new maps will work fine, check the category "Local or redirect" and if the "Map Entry" or/and "Map Cycle" is missing just right click and "Reinstall". After that you will these maps in map cycle.

**Comment by billxsand** [comment]
using KF2ServerTool I updated to beta , made sure the install folder wasn't "read only", but it just wouldn't show up
I also tried "reinstall" or "force update" under Maps but neither worked


What I had to do was use Steam CMD and "app_update #######", then when I re-opened KF2ServerTool it showed up and everything was fine.
