### ISSUE TITLE
Add Map  > Manual is greyed out

### ISSUE THREAD

**Issue by billxsand** [darkdks/KF2ServerTool#7]
Would like to add a .kfm map i have saved on my drive, but Add Map > Manual is greyed out

Can't figure out how to fix it

Any ideas?

The map is deprecated and not on the Steam Workshop

**Comment by darkdks** [comment]
This is a function that will be implemented in future. 
You still able to copy the .kfm to KFGame\BrewedPC\Maps folder and use the tool to register the map in the server. Please note for you clients download the map you need upload it to workshop or a redirect.

**Comment by billxsand** [comment]
Thank you!

**Comment by billxsand** [comment]
Hey more of a request so I didn't want to open a new topic but we need an easy way to get rid of the custom map, it stopped showing up in the maps list and to get rid of it I had to go do it manually

**Comment by darkdks** [comment]
It is very easy to remove any map, just right click and remove > full.
If you have any bug with this part report as detailed as possible, with screenshots and more details.

**Comment by billxsand** [comment]
Hey, sorry about that

https://imgur.com/a/OBnmk8v

The problem is that I have added the custom map, it's in the server maplist, I can run it in the server, but I can't actually find it under the maps tab

**Comment by darkdks** [comment]
@billxsand did u checked the option "Only show items that are in current configuration file"?
That can explain why u dont see this map.
If is unchecked, how u installed this map? by application?

**Comment by billxsand** [comment]
> @billxsand the option "Only show items that are in current configuration file" is unchecked?
This was the problem, thank you!
